---
loki:
  commonConfig:
    replication_factor: 3
  useTestSchema: true
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
deploymentMode: SingleBinary
singleBinary:
  replicas: 3
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
