---
name: helm-ci
on:
  pull_request:
    paths:
      - "production/helm/**"

env:
  CT_CONFIGFILE: production/helm/ct.yaml

jobs:
  call-lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Docs
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.11.0
          if ! git diff --exit-code; then
              echo "Documentation not up to date. Please run helm-docs and commit changes!" >&2
              exit 1
          fi

      - name: Lint Yaml
        run: make helm-lint

      - name: Lint Code Base
        uses: docker://github/super-linter:v3.12.0
        env:
          FILTER_REGEX_EXCLUDE: .*(README\.md|Chart\.yaml|NOTES.txt).*
          FILTER_REGEX_INCLUDE: .*production/helm/.*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_YAML: false
          VALIDATE_GO: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-diff:
    name: Publish Rendered Helm Chart Diff
    runs-on: ubuntu-latest
    steps:
      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Add required Helm repositories
        run: |
          helm repo add minio https://charts.min.io/
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add grafana-operator https://grafana.github.io/helm-charts
          helm repo update

      - name: Prepare directories for base and PR branches
        run: |
          mkdir -p ${{ github.workspace }}/base
          mkdir -p ${{ github.workspace }}/pr
          mkdir -p ${{ github.workspace }}/output

      - name: Checkout base branch to 'base' folder within workspace
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: ${{ github.workspace }}/base

      - name: Checkout PR branch to 'pr' folder within workspace
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: ${{ github.workspace }}/pr

      - name: Render Helm chart for each scenario in the base branch
        run: |
          cd ${{ github.workspace }}/base/production/helm/loki
          helm dependency build
          for file in scenarios/*.yaml; do
            helm template loki . -f $file > "${{ github.workspace }}/output/base-$(basename $file .yaml).yaml"
          done

      - name: Render Helm chart for each scenario in the PR branch
        run: |
          cd ${{ github.workspace }}/pr/production/helm/loki
          helm dependency build
          for file in scenarios/*.yaml; do
            helm template loki . -f $file > "${{ github.workspace }}/output/pr-$(basename $file .yaml).yaml"
          done

      - name: Calculate the diff between base and PR rendered manifests for each scenario
        run: |
          ls -lah ${{ github.workspace }}/output/
          for file in ${{ github.workspace }}/output/base-*.yaml; do
            scenario=$(basename $file | sed 's/^base-//')
            diff_output=$(diff "$file" "${{ github.workspace }}/output/pr-$scenario")
            if [ -z "$diff_output" ]; then
              echo "### Scenario: $scenario" >> ${{ github.workspace }}/output/diff.txt
              echo "<details><summary>No changes</summary>" >> ${{ github.workspace }}/output/diff.txt
              echo "No diff" >> ${{ github.workspace }}/output/diff.txt
              echo "</details>" >> ${{ github.workspace }}/output/diff.txt
            else
              echo "### Scenario: $scenario" >> ${{ github.workspace }}/output/diff.txt
              echo "<details><summary>Show diff</summary>" >> ${{ github.workspace }}/output/diff.txt
              echo '```diff' >> ${{ github.workspace }}/output/diff.txt
              echo "$diff_output" >> ${{ github.workspace }}/output/diff.txt
              echo '```' >> ${{ github.workspace }}/output/diff.txt
              echo "</details>" >> ${{ github.workspace }}/output/diff.txt
            fi
          done

      - name: Post diff as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ${{ github.workspace }}/output/diff.txt

  call-test:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.8.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config "${CT_CONFIGFILE}")
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config "${CT_CONFIGFILE}" --check-version-increment=false
        timeout-minutes: 10

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install prometheus operator
        id: install-prometheus
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace prometheus

          helm install prometheus prometheus-community/kube-prometheus-stack \
            --namespace prometheus \
            --set grafana.enabled=false \
            --set prometheus.prometheusSpec.serviceMonitorSelector.matchLabels.release=prometheus

          kubectl --namespace prometheus get pods -l "release=prometheus"
          kubectl --namespace prometheus get services -l "release=prometheus"

      - name: Run chart-testing (install)
        run: |
          changed=$(ct list-changed --config "${CT_CONFIGFILE}")
          if [[ "$changed" == "charts/enterprise-metrics" ]]; then
            # Do not run `ct install` for enterprise-metrics
            exit 0
          fi
          ct install --config "${CT_CONFIGFILE}"
